//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11._10._2018_P
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories_k
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories_k()
        {
            this.ResourceCategories = new HashSet<ResourceCategory>();
        }
    
        public int categotyCode { get; set; }
        public string caregoryName { get; set; }
        public string parentCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceCategory> ResourceCategories { get; set; }
    }
}
