//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11._10._2018_P
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceCategory
    {
        public int resouceCode { get; set; }
        public int categoryCode { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Categories_k Categories_k { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
